import type { PackageId } from "./validations";

export interface PackageData {
  id: PackageId;
  gallery: string[];
}


export const PACKAGES_DATA: Record<PackageId, PackageData> = {
  essential: {
    id: "essential",
    gallery: [
      "/images/locations/camondo-stairs-1.webp",
      "/images/locations/balat-1.webp",
      "/images/packages/essential/istanbul_photographer_10.webp",
      "/images/packages/essential/istanbul_photographer_11.webp",
      "/images/packages/essential/istanbul_photographer_12.webp",
      "/images/packages/essential/istanbul_photographer_13.webp",
      "/images/packages/essential/istanbul_photographer_14.webp",
      "/images/packages/essential/istanbul_photographer_15.webp",
      "/images/packages/essential/istanbul_photoshoot_1.webp",
      "/images/packages/essential/istanbul_photoshoot_2.webp",
      "/images/packages/essential/istanbul_photoshoot_3.webp",
      "/images/packages/essential/istanbul_photoshoot_4.webp",
      "/images/packages/essential/istanbul_photoshoot_5.webp",
      "/images/packages/essential/istanbul_photoshoot_6.webp",
      "/images/packages/essential/istanbul_photoshoot_7.webp",
      "/images/packages/essential/istanbul_photoshoot_8.webp",
    ],
  },
  premium: {
    id: "premium",
    gallery: [
      "/gallery/istanbul_couple_photoshoot_1.webp",
      "/images/locations/ortakoy-1.webp",
      "/images/locations/blue-mosque-1.webp",
      "/images/locations/hagia-sophia-1.webp",
      "/images/packages/premium/istanbul_best_photography_1.webp",
      "/images/packages/premium/istanbul_best_photography_2.webp",
      "/images/packages/premium/istanbul_best_photography_3.webp",
      "/images/packages/premium/istanbul_best_photography_4.webp",
      "/images/packages/premium/istanbul_best_photography_5.webp",
      "/images/packages/premium/istanbul_business_photography.webp",
      "/images/packages/premium/istanbul_couple_photography.webp",
      "/images/packages/premium/istanbul_couple_photography_1.webp",
      "/images/packages/premium/istanbul_couple_photography_2.webp",
      "/images/packages/premium/istanbul_couple_photography_3.webp",
      "/images/packages/premium/istanbul_couple_photography_4.webp",
      "/images/packages/premium/istanbul_couple_photography_5.webp",
      "/images/packages/premium/istanbul_couple_photography_6.webp",
      "/images/packages/premium/istanbul_fashion_photography.webp",
      "/images/packages/premium/istanbul_fashion_photography_1.webp",
      "/images/packages/premium/istanbul_fashion_photography_2.webp",
      "/images/packages/premium/istanbul_travel_photography.webp",
      "/images/packages/premium/istanbul_travel_photography_2.webp",
    ],
  },
  luxury: {
    id: "luxury",
    gallery: [
      "/gallery/istanbul_wedding_photographer.webp",
      "/gallery/istanbul_wedding_photographer_1.webp",
      "/images/locations/ortakoy-hero.webp",
      "/images/locations/galata-tower-hero.webp",
      "/images/locations/blue-mosque-hero.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_1.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_2.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_3.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_4.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_5.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_6.webp",
      "/images/packages/luxury/istanbul_best_couple_photographer_7.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_1.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_2.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_3.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_4.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_5.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_6.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_7.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_8.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_9.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_10.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_11.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_12.webp",
      "/images/packages/luxury/istanbul_celebrity_photographer_13.webp",
    ],
  },
  rooftop: {
    id: "rooftop",
    gallery: [
      "/images/locations/bosphorus-rooftop-hero.webp",
      "/images/packages/rooftop/istanbul_flying_dress_photoshoot_01.webp",
      "/images/packages/rooftop/istanbul_flying_dress_photoshoot.webp",
      "/images/locations/bosphorus-rooftop-1.webp",
      "/images/locations/bosphorus-rooftop-2.webp",
      "/gallery/istanbul_rooftop_photoshoot.webp",
      "/gallery/istanbul_rooftop_photoshoot_2.webp",
      "/images/packages/rooftop/istanbul_rooftop_photoshoot_4.webp",
      "/images/packages/rooftop/istanbul_rooftop_photoshoot_5.webp",
      "/images/packages/rooftop/istanbul_rooftop_photoshoot_7.webp",
      "/images/packages/rooftop/rooftop_galata_photoshoot.webp",
      "/images/packages/rooftop/rooftop_galata_photoshoot_1.webp",
      "/images/packages/rooftop/taht_istanbul_rooftop_photoshoot.webp",
    ],
  },
  "rooftop-swing": {
    id: "rooftop-swing",
    gallery: [
      "/images/packages/rooftop/swing_photoshoot_istanbul.webp",
      "/images/packages/rooftop/swing_photoshoot_istanbul_01.webp",
      "/images/packages/rooftop/swing_photoshoot_istanbul_02.webp",
      "/images/locations/bosphorus-rooftop-hero.webp",
      "/images/locations/bosphorus-rooftop-2.webp",
      "/gallery/istanbul_rooftop_photoshoot.webp",
      "/gallery/istanbul_rooftop_photoshoot_2.webp",
      "/images/packages/rooftop/istanbul_rooftop_photoshoot_4.webp",
      "/images/packages/rooftop/istanbul_rooftop_photoshoot_5.webp",
      "/images/packages/rooftop/istanbul_rooftop_photoshoot_7.webp",
      "/images/packages/rooftop/rooftop_galata_photoshoot.webp",
      "/images/packages/rooftop/rooftop_galata_photoshoot_1.webp",
      "/images/packages/rooftop/taht_istanbul_rooftop_photoshoot.webp",
    ],
  },
  cappadocia: {
    id: "cappadocia",
    gallery: [
      "/images/packages/cappadocia/cappadocia_couple_photoshoot_1.webp",
      "/images/packages/cappadocia/cappadocia_couple_photoshoot_2.webp",
      "/images/packages/cappadocia/cappadocia_couple_photoshoot_3.webp",
      "/images/packages/cappadocia/cappadocia_balloon_photoshoot.webp",
      "/images/packages/cappadocia/cappadocia_canyon_photoshoot.webp",
    ],
  },
};
